"""Dashboard service interfaces."""

from services.ai_report import (
    AIMarketReport,
    AIReportError,
    clear_ai_report_cache,
    load_daily_ai_market_report,
    resolve_ai_report_path,
)
from services.database import (
    ComparableVehicleMetadata,
    DatabaseQualitySnapshot,
    ListingSearchResult,
    VehicleAnalysisSnapshot,
    VehicleTrendPoint,
    clear_comparable_vehicle_metadata_cache,
    count_new_listings_on,
    database_exists,
    get_connection,
    get_project_root,
    list_listing_brands,
    load_comparable_vehicle_metadata,
    load_database_quality,
    load_vehicle_analysis,
    resolve_database_path,
    search_listings,
)
from services.intelligence import (
    BrandIntelligence,
    DailyMarketIntelligence,
    IntelligenceReportError,
    VehicleIntelligence,
    clear_intelligence_cache,
    load_daily_market_intelligence,
    resolve_report_path,
)
from services.peer_benchmarking import PeerBenchmarkReport, load_peer_benchmarks
from services.pipeline_status import (
    PIPELINE_STAGES,
    PipelineStatus,
    PipelineStatusError,
    clear_pipeline_status_cache,
    load_pipeline_status,
)

__all__ = [
    "AIMarketReport",
    "AIReportError",
    "BrandIntelligence",
    "ComparableVehicleMetadata",
    "DailyMarketIntelligence",
    "DatabaseQualitySnapshot",
    "IntelligenceReportError",
    "ListingSearchResult",
    "PIPELINE_STAGES",
    "PipelineStatus",
    "PipelineStatusError",
    "PeerBenchmarkReport",
    "VehicleAnalysisSnapshot",
    "VehicleIntelligence",
    "VehicleTrendPoint",
    "clear_ai_report_cache",
    "clear_comparable_vehicle_metadata_cache",
    "clear_intelligence_cache",
    "clear_pipeline_status_cache",
    "count_new_listings_on",
    "database_exists",
    "get_connection",
    "get_project_root",
    "list_listing_brands",
    "load_daily_ai_market_report",
    "load_daily_market_intelligence",
    "load_comparable_vehicle_metadata",
    "load_database_quality",
    "load_pipeline_status",
    "load_peer_benchmarks",
    "load_vehicle_analysis",
    "resolve_ai_report_path",
    "resolve_database_path",
    "resolve_report_path",
    "search_listings",
]
