"""create initial database schema

Revision ID: 26591d9c4240
Revises:
Create Date: 2026-07-18 02:29:20.472749

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26591d9c4240"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("canonical_brand", sa.String(length=100), nullable=False),
        sa.Column("chinese_brand", sa.String(length=100), nullable=True),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("country_of_origin", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("brand_id", name=op.f("pk_brands")),
        sa.UniqueConstraint("canonical_brand", name=op.f("uq_brands_canonical_brand")),
    )
    op.create_table(
        "data_quality_issues",
        sa.Column("data_quality_issue_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=False),
        sa.Column("issue_code", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("resolution_status", sa.String(length=50), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "resolution_status IN ("
            "'open', 'investigating', 'resolved', 'accepted', 'ignored'"
            ")",
            name=op.f("ck_data_quality_issues_resolution_status_allowed"),
        ),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'informational')",
            name=op.f("ck_data_quality_issues_severity_allowed"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= detected_at",
            name=op.f("ck_data_quality_issues_resolution_window_valid"),
        ),
        sa.PrimaryKeyConstraint(
            "data_quality_issue_id", name=op.f("pk_data_quality_issues")
        ),
    )
    op.create_index(
        "ix_data_quality_issues_entity",
        "data_quality_issues",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_quality_issues_resolution_severity",
        "data_quality_issues",
        ["resolution_status", "severity"],
        unique=False,
    )
    op.create_table(
        "data_sources",
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("update_frequency", sa.String(length=50), nullable=False),
        sa.Column("authority_level", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("collection_method", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "authority_level IN ("
            "'primary_authoritative', 'primary_commercial', "
            "'secondary_authoritative', 'secondary_commercial'"
            ")",
            name=op.f("ck_data_sources_authority_level_allowed"),
        ),
        sa.CheckConstraint(
            "collection_method IN ("
            "'manual_download', 'api', 'html_parse', "
            "'browser_automation', 'manual_entry'"
            ")",
            name=op.f("ck_data_sources_collection_method_allowed"),
        ),
        sa.CheckConstraint(
            "source_type IN ("
            "'government', 'industry_association', 'central_bank', "
            "'manufacturer', 'marketplace'"
            ")",
            name=op.f("ck_data_sources_source_type_allowed"),
        ),
        sa.CheckConstraint(
            "update_frequency IN ("
            "'daily', 'weekly', 'monthly', 'quarterly', 'irregular', 'manual'"
            ")",
            name=op.f("ck_data_sources_update_frequency_allowed"),
        ),
        sa.CheckConstraint(
            "active IN (0, 1)", name=op.f("ck_data_sources_active_boolean")
        ),
        sa.CheckConstraint(
            "length(country_code) = 2", name=op.f("ck_data_sources_country_code_length")
        ),
        sa.PrimaryKeyConstraint("data_source_id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("source_id", name=op.f("uq_data_sources_source_id")),
    )
    op.create_table(
        "collection_batches",
        sa.Column("collection_batch_id", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=120), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=True),
        sa.Column("collection_method", sa.String(length=50), nullable=False),
        sa.Column("collection_job_id", sa.String(length=120), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("success_count", sa.Integer(), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=True),
        sa.Column("source_file_name", sa.String(length=500), nullable=True),
        sa.Column("raw_file_path", sa.String(length=1000), nullable=True),
        sa.Column("raw_payload_reference", sa.String(length=500), nullable=True),
        sa.Column("parser_version", sa.String(length=120), nullable=True),
        sa.Column("checksum", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "collection_method IN ("
            "'manual_download', 'api', 'html_parse', "
            "'browser_automation', 'manual_entry'"
            ")",
            name=op.f("ck_collection_batches_collection_method_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ("
            "'pending', 'running', 'completed', 'partially_completed', "
            "'failed', 'cancelled'"
            ")",
            name=op.f("ck_collection_batches_status_allowed"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_collection_batches_completion_window_valid"),
        ),
        sa.CheckConstraint(
            "failure_count IS NULL OR failure_count >= 0",
            name=op.f("ck_collection_batches_failure_count_non_negative"),
        ),
        sa.CheckConstraint(
            "record_count IS NULL OR record_count >= 0",
            name=op.f("ck_collection_batches_record_count_non_negative"),
        ),
        sa.CheckConstraint(
            "record_count IS NULL OR success_count IS NULL OR "
            "failure_count IS NULL OR success_count + failure_count <= record_count",
            name=op.f("ck_collection_batches_batch_counts_consistent"),
        ),
        sa.CheckConstraint(
            "success_count IS NULL OR success_count >= 0",
            name=op.f("ck_collection_batches_success_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.data_source_id"],
            name=op.f("fk_collection_batches_data_source_id_data_sources"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "collection_batch_id", name=op.f("pk_collection_batches")
        ),
        sa.UniqueConstraint("batch_id", name=op.f("uq_collection_batches_batch_id")),
    )
    op.create_index(
        "ix_collection_batches_batch_id",
        "collection_batches",
        ["batch_id"],
        unique=True,
    )
    op.create_index(
        "ix_collection_batches_source_started",
        "collection_batches",
        ["data_source_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "data_source_categories",
        sa.Column("data_source_category_id", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("data_category", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "data_category IN ("
            "'registrations', 'official_prices', 'listings', "
            "'exchange_rates', 'market_statistics', 'vehicle_specifications'"
            ")",
            name=op.f("ck_data_source_categories_data_category_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.data_source_id"],
            name=op.f("fk_data_source_categories_data_source_id_data_sources"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "data_source_category_id", name=op.f("pk_data_source_categories")
        ),
        sa.UniqueConstraint(
            "data_source_id",
            "data_category",
            name=op.f("uq_data_source_categories_data_source_id"),
        ),
    )
    op.create_index(
        "ix_data_source_categories_category_source",
        "data_source_categories",
        ["data_category", "data_source_id"],
        unique=False,
    )
    op.create_table(
        "exchange_rate_observations",
        sa.Column("exchange_rate_observation_id", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("exchange_rate_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("data_quality_status", sa.String(length=50), nullable=True),
        sa.Column("validation_status", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_quality_status IS NULL OR data_quality_status IN ("
            "'valid', 'warning', 'invalid', 'unknown'"
            ")",
            name=op.f("ck_exchange_rate_observations_data_quality_status_allowed"),
        ),
        sa.CheckConstraint(
            "validation_status IS NULL OR validation_status IN ("
            "'pending', 'passed', 'failed'"
            ")",
            name=op.f("ck_exchange_rate_observations_validation_status_allowed"),
        ),
        sa.CheckConstraint(
            "base_currency <> quote_currency",
            name=op.f("ck_exchange_rate_observations_currency_pair_not_self"),
        ),
        sa.CheckConstraint(
            "exchange_rate > 0",
            name=op.f("ck_exchange_rate_observations_exchange_rate_positive"),
        ),
        sa.CheckConstraint(
            "length(base_currency) = 3",
            name=op.f("ck_exchange_rate_observations_base_currency_length"),
        ),
        sa.CheckConstraint(
            "length(quote_currency) = 3",
            name=op.f("ck_exchange_rate_observations_quote_currency_length"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.data_source_id"],
            name=op.f("fk_exchange_rate_observations_data_source_id_data_sources"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "exchange_rate_observation_id", name=op.f("pk_exchange_rate_observations")
        ),
        sa.UniqueConstraint(
            "data_source_id",
            "base_currency",
            "quote_currency",
            "exchange_rate_date",
            name=op.f("uq_exchange_rate_observations_data_source_id"),
        ),
    )
    op.create_index(
        "ix_exchange_rate_observations_currency_pair_date",
        "exchange_rate_observations",
        ["base_currency", "quote_currency", "exchange_rate_date"],
        unique=False,
    )
    op.create_index(
        "ix_exchange_rate_observations_source_pair_date",
        "exchange_rate_observations",
        ["data_source_id", "base_currency", "quote_currency", "exchange_rate_date"],
        unique=True,
    )
    op.create_table(
        "vehicles",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("canonical_model", sa.String(length=100), nullable=False),
        sa.Column("chinese_model", sa.String(length=100), nullable=True),
        sa.Column("vehicle_segment", sa.String(length=100), nullable=True),
        sa.Column("body_type", sa.String(length=50), nullable=True),
        sa.Column("default_powertrain", sa.String(length=50), nullable=True),
        sa.Column("priority_level", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "priority_level IN ('high', 'medium', 'low')",
            name=op.f("ck_vehicles_priority_level_allowed"),
        ),
        sa.CheckConstraint("active IN (0, 1)", name=op.f("ck_vehicles_active_boolean")),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.brand_id"],
            name=op.f("fk_vehicles_brand_id_brands"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("vehicle_id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint(
            "brand_id", "canonical_model", name=op.f("uq_vehicles_brand_id")
        ),
    )
    op.create_index(
        "ix_vehicles_brand_model",
        "vehicles",
        ["brand_id", "canonical_model"],
        unique=False,
    )
    op.create_index(
        "ix_vehicles_canonical_model", "vehicles", ["canonical_model"], unique=False
    )
    op.create_table(
        "vehicle_aliases",
        sa.Column("vehicle_alias_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("alias_text", sa.String(length=255), nullable=False),
        sa.Column("normalized_alias", sa.String(length=255), nullable=False),
        sa.Column("alias_language", sa.String(length=50), nullable=True),
        sa.Column("alias_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "alias_type IN ('official', 'german', 'english', 'marketplace', 'common')",
            name=op.f("ck_vehicle_aliases_alias_type_allowed"),
        ),
        sa.CheckConstraint(
            "length(alias_text) > 0",
            name=op.f("ck_vehicle_aliases_alias_text_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle_id"],
            name=op.f("fk_vehicle_aliases_vehicle_id_vehicles"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("vehicle_alias_id", name=op.f("pk_vehicle_aliases")),
        sa.UniqueConstraint(
            "normalized_alias", name=op.f("uq_vehicle_aliases_normalized_alias")
        ),
    )
    op.create_index(
        "ix_vehicle_aliases_normalized_alias",
        "vehicle_aliases",
        ["normalized_alias"],
        unique=True,
    )
    op.create_table(
        "vehicle_variants",
        sa.Column("vehicle_variant_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("model_year", sa.String(length=20), nullable=True),
        sa.Column("generation", sa.String(length=100), nullable=True),
        sa.Column("trim_name", sa.String(length=255), nullable=True),
        sa.Column("variant_name", sa.String(length=255), nullable=True),
        sa.Column("edition_name", sa.String(length=255), nullable=True),
        sa.Column("drivetrain", sa.String(length=50), nullable=True),
        sa.Column("transmission", sa.String(length=50), nullable=True),
        sa.Column("powertrain", sa.String(length=50), nullable=True),
        sa.Column("fuel_type", sa.String(length=50), nullable=True),
        sa.Column(
            "battery_capacity_kwh", sa.Numeric(precision=8, scale=2), nullable=True
        ),
        sa.Column("engine_power_kw", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("engine_power_ps", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "active IN (0, 1)", name=op.f("ck_vehicle_variants_active_boolean")
        ),
        sa.CheckConstraint(
            "battery_capacity_kwh IS NULL OR battery_capacity_kwh >= 0",
            name=op.f("ck_vehicle_variants_battery_capacity_kwh_non_negative"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR "
            "effective_to >= effective_from",
            name=op.f("ck_vehicle_variants_effective_window_valid"),
        ),
        sa.CheckConstraint(
            "engine_power_kw IS NULL OR engine_power_kw >= 0",
            name=op.f("ck_vehicle_variants_engine_power_kw_non_negative"),
        ),
        sa.CheckConstraint(
            "engine_power_ps IS NULL OR engine_power_ps >= 0",
            name=op.f("ck_vehicle_variants_engine_power_ps_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle_id"],
            name=op.f("fk_vehicle_variants_vehicle_id_vehicles"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("vehicle_variant_id", name=op.f("pk_vehicle_variants")),
        sa.UniqueConstraint(
            "vehicle_id",
            "model_year",
            "trim_name",
            "variant_name",
            "edition_name",
            "drivetrain",
            name=op.f("uq_vehicle_variants_vehicle_id"),
        ),
    )
    op.create_index(
        "ix_vehicle_variants_vehicle_year",
        "vehicle_variants",
        ["vehicle_id", "model_year"],
        unique=False,
    )
    op.create_table(
        "marketplace_listings",
        sa.Column("marketplace_listing_id", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("source_listing_id", sa.String(length=255), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=True),
        sa.Column("vehicle_variant_id", sa.Integer(), nullable=True),
        sa.Column("raw_brand", sa.String(length=255), nullable=True),
        sa.Column("raw_model", sa.String(length=255), nullable=True),
        sa.Column("raw_variant_name", sa.String(length=255), nullable=True),
        sa.Column("model_year", sa.String(length=20), nullable=True),
        sa.Column("first_registration_date", sa.Date(), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("owner_count", sa.Integer(), nullable=True),
        sa.Column("seller_type", sa.String(length=50), nullable=True),
        sa.Column("dealer_name", sa.String(length=255), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "condition IS NULL OR condition IN ("
            "'new', 'used', 'demonstrator', 'unknown'"
            ")",
            name=op.f("ck_marketplace_listings_condition_allowed"),
        ),
        sa.CheckConstraint(
            "seller_type IS NULL OR seller_type IN ("
            "'manufacturer', 'dealer', 'private', 'marketplace', 'unknown'"
            ")",
            name=op.f("ck_marketplace_listings_seller_type_allowed"),
        ),
        sa.CheckConstraint(
            "active IN (0, 1)", name=op.f("ck_marketplace_listings_active_boolean")
        ),
        sa.CheckConstraint(
            "country_code IS NULL OR length(country_code) = 2",
            name=op.f("ck_marketplace_listings_country_code_length"),
        ),
        sa.CheckConstraint(
            "last_seen_at IS NULL OR first_seen_at IS NULL OR "
            "last_seen_at >= first_seen_at",
            name=op.f("ck_marketplace_listings_seen_window_valid"),
        ),
        sa.CheckConstraint(
            "mileage_km IS NULL OR mileage_km >= 0",
            name=op.f("ck_marketplace_listings_mileage_km_non_negative"),
        ),
        sa.CheckConstraint(
            "owner_count IS NULL OR owner_count >= 0",
            name=op.f("ck_marketplace_listings_owner_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.data_source_id"],
            name=op.f("fk_marketplace_listings_data_source_id_data_sources"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle_id"],
            name=op.f("fk_marketplace_listings_vehicle_id_vehicles"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.vehicle_variant_id"],
            name=op.f("fk_marketplace_listings_vehicle_variant_id_vehicle_variants"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "marketplace_listing_id", name=op.f("pk_marketplace_listings")
        ),
        sa.UniqueConstraint(
            "data_source_id",
            "source_listing_id",
            name=op.f("uq_marketplace_listings_data_source_id"),
        ),
    )
    op.create_index(
        "ix_marketplace_listings_city", "marketplace_listings", ["city"], unique=False
    )
    op.create_index(
        "ix_marketplace_listings_postal_code",
        "marketplace_listings",
        ["postal_code"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_listings_source_listing",
        "marketplace_listings",
        ["data_source_id", "source_listing_id"],
        unique=True,
    )
    op.create_index(
        "ix_marketplace_listings_variant_active",
        "marketplace_listings",
        ["vehicle_variant_id", "active"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_listings_vehicle_active",
        "marketplace_listings",
        ["vehicle_id", "active"],
        unique=False,
    )
    op.create_table(
        "official_price_observations",
        sa.Column("official_price_observation_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_variant_id", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("collection_batch_id", sa.Integer(), nullable=True),
        sa.Column("official_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_includes_vat", sa.Boolean(), nullable=True),
        sa.Column("valid_date", sa.Date(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_record_id", sa.String(length=255), nullable=True),
        sa.Column("raw_brand", sa.String(length=255), nullable=True),
        sa.Column("raw_model", sa.String(length=255), nullable=True),
        sa.Column("raw_variant_name", sa.String(length=255), nullable=True),
        sa.Column("data_quality_status", sa.String(length=50), nullable=True),
        sa.Column("validation_status", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_quality_status IS NULL OR data_quality_status IN ("
            "'valid', 'warning', 'invalid', 'unknown'"
            ")",
            name=op.f("ck_official_price_observations_data_quality_status_allowed"),
        ),
        sa.CheckConstraint(
            "validation_status IS NULL OR validation_status IN ("
            "'pending', 'passed', 'failed'"
            ")",
            name=op.f("ck_official_price_observations_validation_status_allowed"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR "
            "effective_to >= effective_from",
            name=op.f("ck_official_price_observations_effective_window_valid"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_official_price_observations_currency_length"),
        ),
        sa.CheckConstraint(
            "official_price >= 0",
            name=op.f("ck_official_price_observations_official_price_non_negative"),
        ),
        sa.CheckConstraint(
            "price_includes_vat IS NULL OR price_includes_vat IN (0, 1)",
            name=op.f("ck_official_price_observations_price_includes_vat_boolean"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_batch_id"],
            ["collection_batches.collection_batch_id"],
            name=op.f(
                "fk_official_price_observations_collection_batch_id_collection_batches"
            ),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.data_source_id"],
            name=op.f("fk_official_price_observations_data_source_id_data_sources"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.vehicle_variant_id"],
            name=op.f(
                "fk_official_price_observations_vehicle_variant_id_vehicle_variants"
            ),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "official_price_observation_id", name=op.f("pk_official_price_observations")
        ),
        sa.UniqueConstraint(
            "vehicle_variant_id",
            "data_source_id",
            "valid_date",
            "official_price",
            name=op.f("uq_official_price_observations_vehicle_variant_id"),
        ),
    )
    op.create_index(
        "ix_official_price_observations_source_valid_date",
        "official_price_observations",
        ["data_source_id", "valid_date"],
        unique=False,
    )
    op.create_index(
        "ix_official_price_observations_variant_valid_date",
        "official_price_observations",
        ["vehicle_variant_id", "valid_date"],
        unique=False,
    )
    op.create_table(
        "registration_observations",
        sa.Column("registration_observation_id", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=True),
        sa.Column("vehicle_variant_id", sa.Integer(), nullable=True),
        sa.Column("canonical_brand", sa.String(length=100), nullable=True),
        sa.Column("canonical_model", sa.String(length=100), nullable=True),
        sa.Column("raw_brand", sa.String(length=255), nullable=True),
        sa.Column("raw_model", sa.String(length=255), nullable=True),
        sa.Column("registration_count", sa.Integer(), nullable=True),
        sa.Column("sales_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sales_metric_type", sa.String(length=50), nullable=False),
        sa.Column("registration_period", sa.String(length=20), nullable=False),
        sa.Column("registration_scope", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("valid_date", sa.Date(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_record_id", sa.String(length=255), nullable=True),
        sa.Column("source_file_name", sa.String(length=500), nullable=True),
        sa.Column("source_page_number", sa.Integer(), nullable=True),
        sa.Column("data_quality_status", sa.String(length=50), nullable=True),
        sa.Column("validation_status", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_quality_status IS NULL OR data_quality_status IN ("
            "'valid', 'warning', 'invalid', 'unknown'"
            ")",
            name=op.f("ck_registration_observations_data_quality_status_allowed"),
        ),
        sa.CheckConstraint(
            "sales_metric_type IN ("
            "'new_registration', 'retail_sales', 'wholesale_sales', "
            "'delivery', 'unknown'"
            ")",
            name=op.f("ck_registration_observations_sales_metric_type_allowed"),
        ),
        sa.CheckConstraint(
            "validation_status IS NULL OR validation_status IN ("
            "'pending', 'passed', 'failed'"
            ")",
            name=op.f("ck_registration_observations_validation_status_allowed"),
        ),
        sa.CheckConstraint(
            "country_code IS NULL OR length(country_code) = 2",
            name=op.f("ck_registration_observations_country_code_length"),
        ),
        sa.CheckConstraint(
            "registration_count IS NULL OR registration_count >= 0",
            name=op.f("ck_registration_observations_registration_count_non_negative"),
        ),
        sa.CheckConstraint(
            "sales_value IS NULL OR sales_value >= 0",
            name=op.f("ck_registration_observations_sales_value_non_negative"),
        ),
        sa.CheckConstraint(
            "source_page_number IS NULL OR source_page_number > 0",
            name=op.f("ck_registration_observations_source_page_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.data_source_id"],
            name=op.f("fk_registration_observations_data_source_id_data_sources"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle_id"],
            name=op.f("fk_registration_observations_vehicle_id_vehicles"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.vehicle_variant_id"],
            name=op.f(
                "fk_registration_observations_vehicle_variant_id_vehicle_variants"
            ),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "registration_observation_id", name=op.f("pk_registration_observations")
        ),
        sa.UniqueConstraint(
            "data_source_id",
            "vehicle_id",
            "registration_period",
            "registration_scope",
            "sales_metric_type",
            name=op.f("uq_registration_observations_data_source_id"),
        ),
    )
    op.create_index(
        "ix_registration_observations_scope_metric_period",
        "registration_observations",
        ["registration_scope", "sales_metric_type", "registration_period"],
        unique=False,
    )
    op.create_index(
        "ix_registration_observations_vehicle_period",
        "registration_observations",
        ["vehicle_id", "registration_period"],
        unique=False,
    )
    op.create_table(
        "marketplace_listing_observations",
        sa.Column("marketplace_listing_observation_id", sa.Integer(), nullable=False),
        sa.Column("marketplace_listing_id", sa.Integer(), nullable=False),
        sa.Column("collection_batch_id", sa.Integer(), nullable=True),
        sa.Column("listed_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("price_includes_vat", sa.Boolean(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listing_status", sa.String(length=50), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("data_quality_status", sa.String(length=50), nullable=True),
        sa.Column("validation_status", sa.String(length=50), nullable=True),
        sa.Column("duplicate_key", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_quality_status IS NULL OR data_quality_status IN ("
            "'valid', 'warning', 'invalid', 'unknown'"
            ")",
            name=op.f(
                "ck_marketplace_listing_observations_data_quality_status_allowed"
            ),
        ),
        sa.CheckConstraint(
            "listing_status IN ('active', 'removed', 'sold', 'unavailable', 'unknown')",
            name=op.f("ck_marketplace_listing_observations_listing_status_allowed"),
        ),
        sa.CheckConstraint(
            "validation_status IS NULL OR validation_status IN ("
            "'pending', 'passed', 'failed'"
            ")",
            name=op.f("ck_marketplace_listing_observations_validation_status_allowed"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR length(currency) = 3",
            name=op.f("ck_marketplace_listing_observations_currency_length"),
        ),
        sa.CheckConstraint(
            "listed_price IS NULL OR listed_price >= 0",
            name=op.f("ck_marketplace_listing_observations_listed_price_non_negative"),
        ),
        sa.CheckConstraint(
            "mileage_km IS NULL OR mileage_km >= 0",
            name=op.f("ck_marketplace_listing_observations_mileage_km_non_negative"),
        ),
        sa.CheckConstraint(
            "price_includes_vat IS NULL OR price_includes_vat IN (0, 1)",
            name=op.f("ck_marketplace_listing_observations_price_includes_vat_boolean"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_batch_id"],
            ["collection_batches.collection_batch_id"],
            name=op.f(
                "fk_marketplace_listing_observations_collection_batch_id_"
                "collection_batches"
            ),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_listing_id"],
            ["marketplace_listings.marketplace_listing_id"],
            name=op.f(
                "fk_marketplace_listing_observations_marketplace_listing_id_"
                "marketplace_listings"
            ),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "marketplace_listing_observation_id",
            name=op.f("pk_marketplace_listing_observations"),
        ),
        sa.UniqueConstraint(
            "marketplace_listing_id",
            "observed_at",
            name=op.f("uq_marketplace_listing_observations_marketplace_listing_id"),
        ),
    )
    op.create_index(
        "ix_marketplace_listing_observations_listed_price",
        "marketplace_listing_observations",
        ["listed_price"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_listing_observations_listing_observed",
        "marketplace_listing_observations",
        ["marketplace_listing_id", "observed_at"],
        unique=True,
    )
    op.create_table(
        "estimated_transaction_prices",
        sa.Column("estimated_transaction_price_id", sa.Integer(), nullable=False),
        sa.Column("marketplace_listing_id", sa.Integer(), nullable=True),
        sa.Column("marketplace_listing_observation_id", sa.Integer(), nullable=True),
        sa.Column("vehicle_variant_id", sa.Integer(), nullable=True),
        sa.Column(
            "estimated_transaction_price",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("estimation_method", sa.String(length=120), nullable=False),
        sa.Column("estimation_version", sa.String(length=120), nullable=False),
        sa.Column("confidence_level", sa.String(length=50), nullable=False),
        sa.Column("input_reference", sa.String(length=500), nullable=False),
        sa.Column("estimated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence_level IN ('high', 'medium', 'low', 'unknown')",
            name=op.f("ck_estimated_transaction_prices_confidence_level_allowed"),
        ),
        sa.CheckConstraint(
            "estimated_transaction_price >= 0",
            name=op.f(
                "ck_estimated_transaction_prices_estimated_transaction_price_"
                "non_negative"
            ),
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_estimated_transaction_prices_currency_length"),
        ),
        sa.CheckConstraint(
            "length(estimation_method) > 0",
            name=op.f("ck_estimated_transaction_prices_estimation_method_not_empty"),
        ),
        sa.CheckConstraint(
            "length(estimation_version) > 0",
            name=op.f("ck_estimated_transaction_prices_estimation_version_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_listing_id"],
            ["marketplace_listings.marketplace_listing_id"],
            name=op.f(
                "fk_estimated_transaction_prices_marketplace_listing_id_"
                "marketplace_listings"
            ),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_listing_observation_id"],
            ["marketplace_listing_observations.marketplace_listing_observation_id"],
            name=op.f(
                "fk_estimated_transaction_prices_marketplace_listing_observation_id_"
                "marketplace_listing_observations"
            ),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.vehicle_variant_id"],
            name=op.f(
                "fk_estimated_transaction_prices_vehicle_variant_id_vehicle_variants"
            ),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "estimated_transaction_price_id",
            name=op.f("pk_estimated_transaction_prices"),
        ),
        sa.UniqueConstraint(
            "input_reference",
            "estimation_method",
            "estimation_version",
            "estimated_at",
            name=op.f("uq_estimated_transaction_prices_input_reference"),
        ),
    )
    op.create_index(
        "ix_estimated_transaction_prices_confidence_estimated",
        "estimated_transaction_prices",
        ["confidence_level", "estimated_at"],
        unique=False,
    )
    op.create_index(
        "ix_estimated_transaction_prices_variant_estimated",
        "estimated_transaction_prices",
        ["vehicle_variant_id", "estimated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_estimated_transaction_prices_variant_estimated",
        table_name="estimated_transaction_prices",
    )
    op.drop_index(
        "ix_estimated_transaction_prices_confidence_estimated",
        table_name="estimated_transaction_prices",
    )
    op.drop_table("estimated_transaction_prices")
    op.drop_index(
        "ix_marketplace_listing_observations_listing_observed",
        table_name="marketplace_listing_observations",
    )
    op.drop_index(
        "ix_marketplace_listing_observations_listed_price",
        table_name="marketplace_listing_observations",
    )
    op.drop_table("marketplace_listing_observations")
    op.drop_index(
        "ix_registration_observations_vehicle_period",
        table_name="registration_observations",
    )
    op.drop_index(
        "ix_registration_observations_scope_metric_period",
        table_name="registration_observations",
    )
    op.drop_table("registration_observations")
    op.drop_index(
        "ix_official_price_observations_variant_valid_date",
        table_name="official_price_observations",
    )
    op.drop_index(
        "ix_official_price_observations_source_valid_date",
        table_name="official_price_observations",
    )
    op.drop_table("official_price_observations")
    op.drop_index(
        "ix_marketplace_listings_vehicle_active", table_name="marketplace_listings"
    )
    op.drop_index(
        "ix_marketplace_listings_variant_active", table_name="marketplace_listings"
    )
    op.drop_index(
        "ix_marketplace_listings_source_listing", table_name="marketplace_listings"
    )
    op.drop_index(
        "ix_marketplace_listings_postal_code", table_name="marketplace_listings"
    )
    op.drop_index("ix_marketplace_listings_city", table_name="marketplace_listings")
    op.drop_table("marketplace_listings")
    op.drop_index("ix_vehicle_variants_vehicle_year", table_name="vehicle_variants")
    op.drop_table("vehicle_variants")
    op.drop_index("ix_vehicle_aliases_normalized_alias", table_name="vehicle_aliases")
    op.drop_table("vehicle_aliases")
    op.drop_index("ix_vehicles_canonical_model", table_name="vehicles")
    op.drop_index("ix_vehicles_brand_model", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(
        "ix_exchange_rate_observations_source_pair_date",
        table_name="exchange_rate_observations",
    )
    op.drop_index(
        "ix_exchange_rate_observations_currency_pair_date",
        table_name="exchange_rate_observations",
    )
    op.drop_table("exchange_rate_observations")
    op.drop_index(
        "ix_data_source_categories_category_source", table_name="data_source_categories"
    )
    op.drop_table("data_source_categories")
    op.drop_index(
        "ix_collection_batches_source_started", table_name="collection_batches"
    )
    op.drop_index("ix_collection_batches_batch_id", table_name="collection_batches")
    op.drop_table("collection_batches")
    op.drop_table("data_sources")
    op.drop_index(
        "ix_data_quality_issues_resolution_severity", table_name="data_quality_issues"
    )
    op.drop_index("ix_data_quality_issues_entity", table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    op.drop_table("brands")
    # ### end Alembic commands ###
